export enum ActionType {
  CREATE_POST = 'CREATE_POST',
  RETRIEVE_POST = 'RETRIEVE_POST',
  UPDATE_POST = 'UPDATE_POST',
  DELETE_POST = 'DELETE_POST',
  GET_ALL_POSTS = 'GET_ALL_POSTS', 
  CREATE_COMMENT = 'CREATE_COMMENT'
};